// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnCVQD1rZ-0sK2_ivYDHCwrYDDjDBwaNo',
    appId: '1:254288092317:web:129244fdde678fc6438874',
    messagingSenderId: '254288092317',
    projectId: 'wordivate-c51e7',
    authDomain: 'wordivate-c51e7.firebaseapp.com',
    storageBucket: 'wordivate-c51e7.firebasestorage.app',
    measurementId: 'G-CB0EY9FRMV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3TlnU9Lc4XEJOcxm_y3GB5-xEorSlRkk',
    appId: '1:254288092317:android:da8697ceda9ff8e3438874',
    messagingSenderId: '254288092317',
    projectId: 'wordivate-c51e7',
    storageBucket: 'wordivate-c51e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeqp8XklUMix2hnR0wWG3LC9t-9e9BcW4',
    appId: '1:254288092317:ios:65679fb2a7881d22438874',
    messagingSenderId: '254288092317',
    projectId: 'wordivate-c51e7',
    storageBucket: 'wordivate-c51e7.firebasestorage.app',
    iosBundleId: 'com.example.wordivate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeqp8XklUMix2hnR0wWG3LC9t-9e9BcW4',
    appId: '1:254288092317:ios:65679fb2a7881d22438874',
    messagingSenderId: '254288092317',
    projectId: 'wordivate-c51e7',
    storageBucket: 'wordivate-c51e7.firebasestorage.app',
    iosBundleId: 'com.example.wordivate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnCVQD1rZ-0sK2_ivYDHCwrYDDjDBwaNo',
    appId: '1:254288092317:web:fc74a4d439a7ac67438874',
    messagingSenderId: '254288092317',
    projectId: 'wordivate-c51e7',
    authDomain: 'wordivate-c51e7.firebaseapp.com',
    storageBucket: 'wordivate-c51e7.firebasestorage.app',
    measurementId: 'G-LSHEQCZ1W3',
  );
}
